{{ config(
    materialized = 'table'
) }}

SELECT

    
    DATE(EVENT_TIMESTAMP) AS SALES_DATE,

    YEAR(EVENT_TIMESTAMP) AS SALES_YEAR,

    MONTH(EVENT_TIMESTAMP) AS SALES_MONTH,

    MONTHNAME(EVENT_TIMESTAMP) AS SALES_MONTH_NAME,

    WEEK(EVENT_TIMESTAMP) AS SALES_WEEK,

    DAYOFWEEK(EVENT_TIMESTAMP) AS DAY_OF_WEEK_NUMBER,

    DAYNAME(EVENT_TIMESTAMP) AS DAY_OF_WEEK_NAME,

    
    STORE_ID,
    STORE_NAME,
    STORE_CITY,
    STORE_STATE,

    PRODUCT_ID,
    PRODUCT_NAME,
    PRODUCT_BRAND,
    PRODUCT_CATEGORY,

    CUSTOMER_SEGMENT,

    
    COUNT(DISTINCT EVENT_ID) AS TOTAL_SALES,

    SUM(QUANTITY) AS TOTAL_UNITS_SOLD,

    SUM(TOTAL_AMOUNT_INR) AS TOTAL_REVENUE_INR,

    ROUND(
        SUM(TOTAL_AMOUNT_INR)
        / NULLIF(COUNT(DISTINCT EVENT_ID), 0),
        2
    ) AS AVERAGE_SALE_VALUE_INR

FROM {{ ref('fact_retail_events') }}

WHERE EVENT_TYPE = 'SALE'

GROUP BY

    DATE(EVENT_TIMESTAMP),

    YEAR(EVENT_TIMESTAMP),

    MONTH(EVENT_TIMESTAMP),

    MONTHNAME(EVENT_TIMESTAMP),

    WEEK(EVENT_TIMESTAMP),

    DAYOFWEEK(EVENT_TIMESTAMP),

    DAYNAME(EVENT_TIMESTAMP),

    STORE_ID,
    STORE_NAME,
    STORE_CITY,
    STORE_STATE,

    PRODUCT_ID,
    PRODUCT_NAME,
    PRODUCT_BRAND,
    PRODUCT_CATEGORY,

    CUSTOMER_SEGMENT
    order by sales_date desc