use database E_COM_S3;
use schema bronze;

CREATE OR REPLACE TABLE bronze.BRONZE_RETAIL_EVENTS (
    EVENT_DATA VARIANT,
    SOURCE_FILE_NAME VARCHAR,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO BRONZE_RETAIL_EVENTS (
    EVENT_DATA,
    SOURCE_FILE_NAME
)
FROM (
    SELECT
        $1,
        METADATA$FILENAME
    FROM @STG_RETAIL_HISTORICAL
)
FILE_FORMAT = (
    TYPE = JSON
)
ON_ERROR = 'CONTINUE';

select count(*) from bronze.bronze_retail_events;