use database e_com_s3;
use schema bronze;

CREATE OR REPLACE PIPE PIPE_RETAIL_EVENTS
AUTO_INGEST = TRUE
AS
COPY INTO BRONZE_RETAIL_EVENTS 
( 
EVENT_DATA, SOURCE_FILE_NAME, LOAD_TIMESTAMP 
)
FROM
( 
SELECT
    $1, 
    METADATA$FILENAME, 
    CURRENT_TIMESTAMP() 
    FROM @BRONZE.STG_RETAIL_HISTORICAL 
) 
    FILE_FORMAT = ( TYPE = JSON ) 
    ON_ERROR = CONTINUE;

desc pipe PIPE_RETAIL_EVENTS;